package main

import (
	"crypto/hmac"
	"crypto/sha256"
	"encoding/csv"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"kemowbench/sha3"

	"kemowbench/kemchcca"
	"kemowbench/kempca"
)

type Result struct {
	ServerPK time.Duration
	ClientPK time.Duration
	ServerSK time.Duration
	ClientSK time.Duration
}

func main() {
	iters := flag.Int("iters", 1000, "number of PAKE sessions")
	pwStr := flag.String("pw", "password", "password used for client key derivation")
	outDir := flag.String("out", "out", "output directory")
	flag.Parse()

	ctx := []byte("ctx")
	pw := []byte(*pwStr)

	kemS := kemchcca.NewMLKEM768CHCCA()
	kemC := kempca.NewPWKyberPKEKEM()

	var acc Result
	for i := 0; i < *iters; i++ {
		// --- Server PK gen ---
		t0 := time.Now()
		pkS, skS, err := kemS.KeyGen()
		must(err)
		acc.ServerPK += time.Since(t0)

		// --- Client PK gen (pw-derived) ---
		t1 := time.Now()
		pkC, skC, err := kemC.DeriveKeyPairFromPassword(pw)
		must(err)
		acc.ClientPK += time.Since(t1)

		// --- Client side: Encap_s + K1 ---
		t2 := time.Now()
		ctS, ssS_client, err := kemS.Encap(pkS)
		must(err)
		_ = ssS_client
		// K1 (discarded in benchmark, but we include it in shared-key pipeline)
		_ = pakeRunHKDF(ssS_client, ctx)
		acc.ClientSK += time.Since(t2)

		// --- Server side: Decap_s + Encap_c + IC/HMAC/HKDF ---
		t3 := time.Now()
		ssS_server, err := kemS.Decap(skS, ctS)
		must(err)
		_ = pakeRunHKDF(ssS_server, ctx)
		ctC, ssC_server, err := kemC.Encap(pkC)
		must(err)
		eC := pakeRunIC(ssS_server, pkC, ctx, ctC)
		AuthS := pakeRunAuth(ssS_server, ssC_server, ctx)
		K_server := pakeRunSession(ssS_server, ssC_server, ctx)
		_ = K_server
		acc.ServerSK += time.Since(t3)

		// --- Client side: IC.Dec + Decap_c + HMAC + HKDF ---
		t4 := time.Now()
		ctC2 := pakeRunIC(ssS_client, pkC, ctx, eC) // xor again to decrypt
		ssC_client, err := kemC.Decap(skC, ctC2)
		must(err)
		AuthC := pakeRunAuth(ssS_client, ssC_client, ctx)
		if !equal(AuthC, AuthS) {
			panic("auth mismatch")
		}
		K_client := pakeRunSession(ssS_client, ssC_client, ctx)
		_ = K_client
		acc.ClientSK += time.Since(t4)
	}

	avg := Result{
		ServerPK: acc.ServerPK / time.Duration(*iters),
		ClientPK: acc.ClientPK / time.Duration(*iters),
		ServerSK: acc.ServerSK / time.Duration(*iters),
		ClientSK: acc.ClientSK / time.Duration(*iters),
	}

	must(os.MkdirAll(*outDir, 0o755))
	writeCSV(*outDir, avg)
	writeLaTeXTable(*outDir, avg)
	writePGFPlots(*outDir, avg)

	fmt.Printf("Average over %d runs:\n", *iters)
	fmt.Printf("  ServerPK: %v\n", avg.ServerPK)
	fmt.Printf("  ClientPK: %v\n", avg.ClientPK)
	fmt.Printf("  ServerSK: %v\n", avg.ServerSK)
	fmt.Printf("  ClientSK: %v\n", avg.ClientSK)
}

func writeCSV(outDir string, r Result) {
	f := mustCreate(filepath.Join(outDir, "results.csv"))
	defer f.Close()
	w := csv.NewWriter(f)
	_ = w.Write([]string{"metric", "avg_ms"})
	_ = w.Write([]string{"ServerPK-time", fmt.Sprintf("%.6f", durMS(r.ServerPK))})
	_ = w.Write([]string{"ClientPK-time", fmt.Sprintf("%.6f", durMS(r.ClientPK))})
	_ = w.Write([]string{"ServerSK-time", fmt.Sprintf("%.6f", durMS(r.ServerSK))})
	_ = w.Write([]string{"ClientSK-time", fmt.Sprintf("%.6f", durMS(r.ClientSK))})
	w.Flush()
}

func writeLaTeXTable(outDir string, r Result) {
	f := mustCreate(filepath.Join(outDir, "results.tex"))
	defer f.Close()
	fmt.Fprintln(f, "% Auto-generated by kemowbench")
	fmt.Fprintln(f, "\\begin{table}[htb]")
	fmt.Fprintln(f, "\\centering")
	fmt.Fprintln(f, "\\begin{tabular}{l c}")
	fmt.Fprintln(f, "\\hline")
	fmt.Fprintln(f, "Metric & Avg. time (ms) \\\\")
	fmt.Fprintln(f, "\\hline")
	fmt.Fprintf(f, "ServerPK-time & %.3f \\\\\n", durMS(r.ServerPK))
	fmt.Fprintf(f, "ClientPK-time & %.3f \\\\\n", durMS(r.ClientPK))
	fmt.Fprintf(f, "ServerSK-time & %.3f \\\\\n", durMS(r.ServerSK))
	fmt.Fprintf(f, "ClientSK-time & %.3f \\\\\n", durMS(r.ClientSK))
	fmt.Fprintln(f, "\\hline")
	fmt.Fprintln(f, "\\end{tabular}")
	fmt.Fprintln(f, "\\caption{Average runtime of public-key generation and shared-key derivation (1000 runs).}")
	fmt.Fprintln(f, "\\label{tab:pake-runtime}")
	fmt.Fprintln(f, "\\end{table}")
}

func writePGFPlots(outDir string, r Result) {
	f := mustCreate(filepath.Join(outDir, "barplot.tex"))
	defer f.Close()
	fmt.Fprintln(f, "% Auto-generated by kemowbench")
	fmt.Fprintln(f, "\\begin{figure}[htb]")
	fmt.Fprintln(f, "\\centering")
	fmt.Fprintln(f, "\\begin{tikzpicture}")
	fmt.Fprintln(f, "\\begin{axis}[")
	fmt.Fprintln(f, "ybar,")
	fmt.Fprintln(f, "bar width=14pt,")
	fmt.Fprintln(f, "width=0.9\\textwidth,")
	fmt.Fprintln(f, "height=6cm,")
	fmt.Fprintln(f, "ylabel={Runtime (ms)},")
	fmt.Fprintln(f, "symbolic x coords={ServerPK-time,ClientPK-time,ServerSK-time,ClientSK-time},")
	fmt.Fprintln(f, "xtick=data,")
	fmt.Fprintln(f, "x tick label style={rotate=0,anchor=north},")
	fmt.Fprintln(f, "grid=both,")
	fmt.Fprintln(f, "]")
	fmt.Fprintln(f, "\\addplot+[fill=blue!35, draw=black] coordinates {")
	fmt.Fprintf(f, "(ServerPK-time, %.6f)\n", durMS(r.ServerPK))
	fmt.Fprintf(f, "(ClientPK-time, %.6f)\n", durMS(r.ClientPK))
	fmt.Fprintf(f, "(ServerSK-time, %.6f)\n", durMS(r.ServerSK))
	fmt.Fprintf(f, "(ClientSK-time, %.6f)\n", durMS(r.ClientSK))
	fmt.Fprintln(f, "};")
	fmt.Fprintln(f, "\\end{axis}")
	fmt.Fprintln(f, "\\end{tikzpicture}")
	fmt.Fprintln(f, "\\caption{Runtime of public-key generation and shared-key derivation.}")
	fmt.Fprintln(f, "\\label{fig:pake-runtime}")
	fmt.Fprintln(f, "\\end{figure}")
}

func durMS(d time.Duration) float64 {
	return float64(d) / float64(time.Millisecond)
}

func must(err error) {
	if err != nil {
		panic(err)
	}
}

func mustCreate(p string) *os.File {
	f, err := os.Create(p)
	must(err)
	return f
}

// ---- Small helpers that mirror the PAKE computations to time them explicitly ----

func pakeRunHKDF(ss, ctx []byte) []byte {
	// Use the full protocol once to reuse correct implementations.
	// Here we call a private helper by reusing pake.Run via an isolated path.
	// For timing we just return a fixed-length HKDF output.
	return pakeHKDFExpand(ss, ctx, 32)
}

func pakeRunIC(ssS, pkC, ctx, in []byte) []byte {
	key := pakeHKDFExpand(append(ssS, pkC...), ctx, len(in))
	return pakeICXor(key, ctx, in)
}

func pakeRunAuth(ssS, ssC, ctx []byte) []byte {
	return pakeHMACTag(ssS, ssC, ctx)
}

func pakeRunSession(ssS, ssC, ctx []byte) []byte {
	return pakeHKDFExpand(append(ssS, ssC...), ctx, 32)
}

// Local re-implementations (must match pake/pq_pake.go)

func pakeHKDFExpand(ikm, info []byte, outLen int) []byte {
	// Use crypto/hkdf via stdlib
	// (We keep it here to avoid exporting internals from package pake.)
	r := hkdfNewSHA256(ikm, info)
	out := make([]byte, outLen)
	_, _ = r.Read(out)
	return out
}

// minimal hkdf reader
func hkdfNewSHA256(ikm, info []byte) *hkdfReader {
	return newHKDFReader(ikm, info)
}

// --- HKDF (HMAC-SHA256) minimal implementation ---
// We avoid importing non-stdlib packages.

type hkdfReader struct {
	prk  []byte
	info []byte
	n    byte
	buf  []byte
}

func newHKDFReader(ikm, info []byte) *hkdfReader {
	// Extract with empty salt
	prk := hmacSHA256(nil, ikm)
	return &hkdfReader{prk: prk, info: info, n: 0, buf: nil}
}

func (r *hkdfReader) Read(p []byte) (int, error) {
	written := 0
	for written < len(p) {
		if len(r.buf) == 0 {
			r.n++
			r.buf = hkdfExpandBlock(r.prk, r.buf, r.info, r.n)
		}
		n := copy(p[written:], r.buf)
		r.buf = r.buf[n:]
		written += n
	}
	return written, nil
}

func hkdfExpandBlock(prk, prev, info []byte, counter byte) []byte {
	m := make([]byte, 0, len(prev)+len(info)+1)
	m = append(m, prev...)
	m = append(m, info...)
	m = append(m, counter)
	return hmacSHA256(prk, m)
}

func hmacSHA256(key, msg []byte) []byte {
	mac := hmac.New(sha256.New, key)
	mac.Write(msg)
	return mac.Sum(nil)
}

func pakeHMACTag(ssS, ssC, ctx []byte) []byte {
	mac := hmac.New(sha256.New, append(ssS, ssC...))
	mac.Write(ctx)
	return mac.Sum(nil)
}

func pakeICXor(key, ctx, ct []byte) []byte {
	// Reuse SHAKE256 from CIRCL (same as package pake)
	xof := sha3.NewShake256()
	xof.Write([]byte("ic-v1"))
	xof.Write([]byte{0})
	xof.Write(key)
	xof.Write([]byte{0})
	xof.Write(ctx)
	ks := make([]byte, len(ct))
	xof.Read(ks)
	out := make([]byte, len(ct))
	for i := range ct {
		out[i] = ct[i] ^ ks[i]
	}
	return out
}

func equal(a, b []byte) bool {
	if len(a) != len(b) {
		return false
	}
	var v byte
	for i := range a {
		v |= a[i] ^ b[i]
	}
	return v == 0
}
